### PR TITLE
6113 Fix menu inside of tables not showing properly

### LINKED ISSUE #6113: Menu inside of tables is rendering behind table footer element (wrong z-index?)
### Environment
* Nautobot version (Docker tag too if applicable): v2.3.0
* Python version:
* Database platform, version:
* Middleware(s):

### Steps to Reproduce
1. Go to https://demo.nautobot.com/dcim/devices/37a938b0-bd5a-4c25-9d98-a51c75d15ba9/interfaces/ or any device interfaces tab of a device that has interfaces
2. Click on the `Connect Cable` button on the last interface in the table

### Expected Behavior

Menu appears above the table

### Observed Behavior

image

### PR DESCRIPTION
**Pull request by mateusz-lachowski-codilime**
# Closes #6113 
# What's Changed
Added custom js code to dynamically attach current dropdown to the body, to override browser behavior when custom overflow is set for `.table-responsive`. Then absolute position is calculated to match the clicked `.dropdown-toggle` button and match right side edges.

# Screenshots
Before:
image
image

After:
image
image

# TODO

- [x] Explanation of Change(s)
- [x] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/core/#creating-changelog-fragments))
- [x] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example App Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

### CODE REVIEW

File: nautobot/project-static/js/dropdown.js [hunk 1]
```diff
@@ -0,0 +1,24 @@
+$(document).on('show.bs.dropdown', '.table-responsive .dropdown', function() {
```
Comment (glennmatthews) [inline nautobot/project-static/js/dropdown.js:1]: This is probably going to go away when we move to Bootstrap v5 anyway, but just in case it will need to live on, can we implement it with vanilla JS instead of jQuery? Or is jQuery necessary to work with the bootstrap 3 event implementation?

Comment (mateusz-lachowski-codilime) [reply nautobot/project-static/js/dropdown.js:1]: It seems like those events are not standard JS events so I would need to either change them and re-fire or just stick with current approach. In theory I can write offset calculating in vanilla js but I think it's more clean this way.

**Comment by mateusz-lachowski-codilime** [comment]
[Screencast from 2025-02-03 16-49-44.webm](https://github.com/user-attachments/assets/96f007e4-294c-44e1-9316-5214ae904d82)

**Review by timizuoebideri1 — APPROVED** [review]
