### PR TITLE
Fixed interface dynamic group filtering

### LINKED ISSUE #8319: Cannot Update DynamicGroup for Interface when 802.1Q mode Tagged or Tagged VLANs are selected
If you create a DynamicGroup and assign it to the ContentType dcim | Interface, you cannot edit the resulting Filter fields to set only a 802.1Q mode of Tagged, or select a list of Tagged VLANs. Both produce form validation errors, leaving no method for setting up a DynamicGroup based on Interface Tagged VLANs. You can update this from the API though, but you have to set `mode` as a list of strings, and VLANs as a list of UUID's. Even after setting in the API though, this is not compatible with the UI form.
```
{
  "filter": {
    "mode": ["tagged"],
    "tagged_vlans": [
      "9feba4b3-9fc8-5298-a6c1-8f0f77378f21",
      "d24c7b32-6e1e-5d2f-b4f3-dd6c4e96a36a"
    ]
  }
}
```

### Environment
* Nautobot version: 3.0.2 (present in 2.4.21 as well)
* Verified and reproduced on Demo site

### Steps to Reproduce
1. Create a new DynamicGroup, set ContentType to `dcim | interface`
2. Edit the new Dynamic Group
3. Select 802.1Q mode “Tagged“ and nothing else
* Error: Enter a list of values.
4. Select 802.1Q mode “Tagged“ and any tagged VLAN
* Error: “\<UUID\>” is not a valid value.

### Expected Behavior
802.1Q mode and Tagged VLANs filter fields should work on the DynamicGroup Edit form

### Observed Behavior
Validation errors, due to form field handling

### PR DESCRIPTION
**Pull request by joewesch**
# Closes #8319 
# What's Changed

This PR adds explicit Interface filter definitions for the mode, duplex, tagged_vlans and untagged_vlan fields. This fixes the ability to use these fields as filters for an interface dynamic group.
# Screenshots

Screenshot 2026-02-05 at 1 44 37 PM
Screenshot 2026-02-05 at 1 44 43 PM

# TODO

- [x] Explanation of Change(s)
- [x] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/core/#creating-changelog-fragments))
- [x] Attached Screenshots, Payload Example
- [x] Unit, Integration Tests

NTC-4667

### CODE REVIEW

File: nautobot/project-static/js/forms.js [hunk 1]
```diff
@@ -176,8 +176,15 @@ function initializeVLANModeSelection(context) {
...
-        const $rowTagged = $tagged.parent().parent();
+        // Find the container div for the field row
+        // In filter drawer: .nb-form-group contains the field directly
+        // In regular forms: .mb-10.d-md-flex contains the field (via .col-md-9 wrapper)
+        const $rowUntagged = $untagged.closest(".nb-form-group").length 
+            ? $untagged.closest(".nb-form-group")
+            : $untagged.closest(".mb-10");
+        const $rowTagged = $tagged.closest(".nb-form-group").length 
+            ? $tagged.closest(".nb-form-group")
+            : $tagged.closest(".mb-10");
```
Comment (joewesch) [inline nautobot/project-static/js/forms.js]: This fix was unrelated, but I stumbled upon a bug that was introduced as part of #8447.

Essentially, once I added the 3 fields to the filter form (mode, tagged_vlans & untagged_vlan) it caused the entire filter form to disappear.
Screenshot 2026-02-05 at 9 46 51 AM

I noticed in the html that `d-none` was getting added in:
Screenshot 2026-02-05 at 9 46 57 AM

That helped narrow down to this code (thanks for the pointer @norbert-mieczkowski-codilime). Full disclosure, I asked AI to fix this, but since @itdependsnetworks vibe coded the original code maybe it was kismet. I verified that the dropdown fields still work on the interface edit form (the fix for 8447) so there should not be a regression at least.

Screenshot 2026-02-05 at 2 01 27 PM

Comment (joewesch) [reply nautobot/project-static/js/forms.js]: Norbert mentioned that `mb-10` was a fragile selector so I had AI rewrite it to be a bit more robust.

File: nautobot/dcim/forms.py [hunk 2]
```diff
@@ -3178,6 +3178,16 @@ class InterfaceFilterForm(ModularDeviceComponentFilterForm, RoleModelFilterFormM
...
     enabled = forms.NullBooleanField(required=False, widget=StaticSelect2(choices=BOOLEAN_WITH_BLANK_CHOICES))
     mgmt_only = forms.NullBooleanField(required=False, widget=StaticSelect2(choices=BOOLEAN_WITH_BLANK_CHOICES))
+    duplex = forms.MultipleChoiceField(choices=InterfaceDuplexChoices, required=False, widget=StaticSelect2Multiple())
+    mode = forms.MultipleChoiceField(
+        choices=InterfaceModeChoices,
+        required=False,
+        label="802.1Q Mode",
+        help_text=INTERFACE_MODE_HELP_TEXT,
+        widget=StaticSelect2Multiple(),
+    )
```
Comment (glennmatthews) [inline nautobot/dcim/forms.py:3188]: For my education, do you have any insight into what was wrong/missing from the default autogenerated form fields for these two?

File: nautobot/extras/tests/test_views.py [hunk 3]
```diff
@@ -2245,6 +2246,35 @@ def test_edit_object_with_content_type_ipam_prefix(self):
...
+        request = {
+            "path": self._get_url("edit", instance),
+            "data": post_data(data),
+        }
+        self.assertHttpStatus(self.client.post(**request), 302)
+        instance.refresh_from_db()
+        self.assertEqual(instance.filter["mode"], [InterfaceModeChoices.MODE_TAGGED])
+        self.assertEqual(instance.filter["duplex"], [InterfaceDuplexChoices.DUPLEX_FULL])
+        self.assertEqual(instance.filter["tagged_vlans"], [str(VLAN.objects.first().pk)])
+        self.assertEqual(instance.filter["untagged_vlan"], [str(VLAN.objects.last().pk)])
```
Comment (glennmatthews) [inline nautobot/extras/tests/test_views.py]: Would it be useful/worthwhile to augment this test to check that the members of the updated dynamic group are correctly calculated? Fine if that's out of scope for the bug in question.

File: nautobot/dcim/forms.py (hunk 2 above)
Comment (joewesch) [reply nautobot/dcim/forms.py:3188]: It looks like default filterset form has a `selectmultiple` widget, but the dynamic group form was defaulting to a ChoiceField so it was only sending one option.

```python
In [1]: from nautobot.dcim.filters import InterfaceFilterSet

In [2]: f = InterfaceFilterSet()

In [3]: f.form["mode"].widget_type
Out[3]: 'selectmultiple'
```

So, it was raising a form validation error of `Enter a list of values.` here:

https://github.com/nautobot/nautobot/blob/e2787bedee2274993c97c722bb90ebe3991aa5a4/nautobot/extras/models/groups.py#L540-L544

File: nautobot/extras/tests/test_views.py (hunk 3 above)
Comment (joewesch) [reply nautobot/extras/tests/test_views.py]: Added.

File: nautobot/dcim/forms.py (hunk 2 above)
Comment (glennmatthews) [reply nautobot/dcim/forms.py:3188]: Thanks, that gives me a couple of ideas. I note that on `InterfaceFilterSet`, `duplex` is explicitly declared as a `MultipleChoiceFilter`, while `mode` is not explicitly declared (and therefore I *think* defaulting to a `MultiValueCharFilter` from our base NautobotFilterSet class). I wonder if that's relevant to the bug.  Not blocking by any means but it might be interesting to investigate further.

File: nautobot/extras/tests/test_views.py [hunk 4]
```diff
@@ -2275,6 +2275,23 @@ def test_edit_object_with_content_type_dcim_interface(self):
...
+        filtered_qs = Interface.objects.filter(
+            mode=InterfaceModeChoices.MODE_TAGGED,
+            duplex=InterfaceDuplexChoices.DUPLEX_FULL,
+            tagged_vlans=VLAN.objects.first().pk,
+            untagged_vlan=VLAN.objects.last().pk,
+        ).distinct()
+
+        group_members = instance.update_cached_members()
+        # The interface queryset and the group members should match
+        self.assertEqual(
```
Comment (glennmatthews) [inline nautobot/extras/tests/test_views.py]: can we use `assertQuerySetEqual` or even `assertQuerysetEqualAndNotEmpty`?

Comment (joewesch) [reply nautobot/extras/tests/test_views.py]: Done
